name: naborly_stream_feed_flutter
publish_to: none
environment:
  sdk: '>=3.6.0 <4.0.0'
workspace:
  - packages/faye_dart
  - packages/stream_feed
  - packages/stream_feed_flutter
  - packages/stream_feed_flutter_core
dev_dependencies:
  melos: ^7.1.1

melos:
  scripts:
    p: 
      run: melos exec -c 1 -- flutter pub upgrade --major-versions
