name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 1.8.0
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  dio: ^4.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.1
  stream_feed: ^0.6.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
